[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.29.1",
    "openai>=1.78.1",
    "pandas>=2.2.3",
]
